routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () 
{
    if(Auth::check() && auth::user()->isAdmin == 1)
    {
        return view('admin/index');

    }else if((Auth::check() && auth::user()->isAdmin != 1))
    {
        return redirect('/home');
    }else 
    {
        return view('/home');
    }
});

Auth::routes();

Route::post('/buyticket', 'TicketsController@store')->middleware('auth');


Route::resource('baskets', 'BasketsController');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('places', 'PlacesController');
Route::resource('comments', 'CommentsController');
Route::resource('schedules', 'SchedulesController');
Route::resource('adminPlaces', 'AdminPlaceController');
Route::resource('adminUsers', 'AdminUserController');
Route::resource('Dates', 'DateController');
// Route::resource('tickets', 'TicketsController');

// Route::get('Places/show', 'CommentsController@index');
// Route::resource('Places.show', 'CommentsController');
// Route::get('/places/{places}', 'CommentsController@index');
// Route::get('Places/action', 'LiveSearchController@action')->name('Places.action');

resources/views/admin/index.blade.php
@extends('layouts.appAdmin')
@section('content')
<div class="container mt-4">
    <div class="container">
        <h4 style="color:#245B43">Welcome, <strong>Admin</strong>  </h4>
    </div>
    <br>
    <section class="jumbotron text-center" style="background-color: white">
        <div class="container">
          <h1>Manajemen Plesir Jogja</h1>
          <img src="/images/admin2.png" alt="..." style="width: 350px; height: 350px">
          <p>
              <a href="{{route('adminPlaces.index')}}" class="btn btn-primary btn-lg my-2 mx-2">Obyek Wisata</a>
              <a href="{{route('adminUsers.index')}}" class="btn btn-secondary btn-lg my-2 mx-2">Pengguna</a>
            </p>
        </div>
      </section>
</div>
    
@endsection