routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () 
{
    if(Auth::check() && auth::user()->isAdmin == 1)
    {
        return view('admin/index');

    }else if((Auth::check() && auth::user()->isAdmin != 1))
    {
        return redirect('/home');
    }else 
    {
        return view('/home');
    }
});

Auth::routes();

Route::post('/buyticket', 'TicketsController@store')->middleware('auth');


Route::resource('baskets', 'BasketsController');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('places', 'PlacesController');
Route::resource('comments', 'CommentsController');
Route::resource('schedules', 'SchedulesController');
Route::resource('adminPlaces', 'AdminPlaceController');
Route::resource('adminUsers', 'AdminUserController');
Route::resource('Dates', 'DateController');
// Route::resource('tickets', 'TicketsController');

// Route::get('Places/show', 'CommentsController@index');
// Route::resource('Places.show', 'CommentsController');
// Route::get('/places/{places}', 'CommentsController@index');
// Route::get('Places/action', 'LiveSearchController@action')->name('Places.action');

app/Place.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Place extends Model
{
    protected $fillable =['nama','hari','buka','tutup','harga_tiket','deskripsi','tempat_umum', 'gambar' ];

    public $timestamps = false;

    public function comments()
    {
        return $this->hasMany('App\Comment');
    }

    public function tickets()
    {
        return $this->hasMany('App\Ticket');
    }

    public static function boot() {
        parent::boot();

        static::deleting(function($user) { // before delete() method call this
            $user->comments()->delete();
             // do the rest of the cleanup...
        });
    }

    public function schedules()
    {
        return $this->hasMany('App\Schedule');
    }
}

app/Http/Controllers/PlacesController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Place;
use App\Ticket;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PlacesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $places = Place::all();
        return view('Places.index', compact('places'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    
    public function store(Request $request)
    {
        $this->middleware('auth');
            $place = Place::findOrFail($request->place_id);
            Ticket::create([
                'user_id'    => auth()->id(),
                'place_id'   => $place->id,
                'kode_tiket' => "$request->kode_tiket"
            ]);
        
        
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Place $place)
    {              
        return view('Places.show', compact('place'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/places/addPlace.blade.php
@extends('layouts.appAdmin')

@section('content')
    <div class="container">
   <!-- Remove This Before You Start -->
   <h1>Tambah Destinasi Wisata</h1>
   <hr>
   @if (count($errors) > 0)
   <div class="alert alert-danger">
       <ul>
           @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
           @endforeach
       </ul>
   </div>
   @endif
   <form action="{{ route('adminPlaces.store') }}" method="post" enctype="multipart/form-data">
       {{ csrf_field() }}
       <div class="form-group">
           <label for="name">Nama Destinasi:</label>
           <input type="text" class="form-control" id="" name="name">
       </div>
       <div class="form-group">
            <label for="day">Hari Buka: </label>
            <input type="text" class="form-control" id="" name="day" placeholder="contoh : senin-rabu & jumat-minggu">
        </div>
       <div class="form-group">
           <label for="open">Jam Buka: </label>
           <input type="time" class="form-control" id="" name="open">
       </div>
       <div class="form-group">
           <label for="close">Jam Tutup: </label>
           <input type="time" class="form-control" id="" name="close">
       </div>
       <div class="form-group">
           <label for="price">Harga Tiket:</label>
           <input type="text" class="form-control" id="" name="price">
       </div>
       <div class="form-group">
            <label for="facl">Fasilitas:</label>
            <input type="text" class="form-control" id="" name="facl">
        </div>
       <div class="form-group">
            <label for="desc">Deskripsi:</label>
            <textarea class="form-control" id="alamat" name="desc"></textarea>
        </div>
        <div class="form-group">
            <label for="gambar">Masukkan File Gambar</label>
            <input type="file" name="gambar">
        </div>
       <div class="form-group">
           <button type="submit" class="btn btn-md btn-primary">Submit</button>
           <button type="reset" class="btn btn-md btn-danger">Cancel</button>
       </div>
   </form>

    </div>
@endsection

resources/views/admin/places/editPlace.blade.php
@extends('layouts.appAdmin')

@section('content')
    <div class="container">
   <!-- Remove This Before You Start -->
   <h1>Ubah Destinasi Wisata</h1>
   <hr>
   @if (count($errors) > 0)
   <div class="alert alert-danger">
       <ul>
           @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
           @endforeach
       </ul>
   </div>
   @endif
   <form action="{{ route('adminPlaces.update', $place->id) }}" method="post" enctype="multipart/form-data">
       {{ csrf_field() }}
       @method('PUT')

       <div class="form-group">
           <label for="name">Nama Destinasi:</label>
           <input type="text" class="form-control" id="" name="name" value="{{$place->nama}}">
       </div>
       <div class="form-group ">
            <label for="day">Hari Buka: </label>
            <input type="text" class="form-control" id="" name="day" placeholder="contoh : senin-rabu & jumat-minggu" value="{{$place->hari}}">
        </div>
       <div class="form-group">
           <label for="open">Jam Buka: </label>
           <input type="time" class="form-control" id="" name="open" value="{{$place->buka}}">
       </div>
       <div class="form-group">
           <label for="close">Jam Tutup: </label>
           <input type="time" class="form-control" id="" name="close" value="{{$place->tutup}}">
       </div>
       <div class="form-group">
           <label for="price">Harga Tiket:</label>
           <input type="text" class="form-control" id="" name="price" value="{{$place->harga_tiket}}">
       </div>
       <div class="form-group">
            <label for="facl">Fasilitas:</label>
            <input type="text" class="form-control" id="" name="facl" value="{{$place->tempat_umum}}">
        </div>
       <div class="form-group">
            <label for="desc">Deskripsi:</label>
            <textarea class="form-control" id="alamat" name="desc">{{$place->deskripsi}}</textarea>
        </div>
        <div class="form-group">
            <label for="gambar">Masukkan File Gambar</label>
            <input type="file" name="gambar">
        </div>
       <div class="form-group">
           <button type="submit" class="btn btn-md btn-primary">Submit</button>
           <button type="reset" class="btn btn-md btn-danger">Cancel</button>
       </div>
   </form>

    </div>
@endsection

resources/views/admin/places/index.blade.php
@extends('layouts.appAdmin')
@section('content')
<div class="container mt-4">
            <div class="card mt-2">
                <div class="card-header text-center">
                    <h2><strong>Data Obyek Wisata</strong></h2>
                </div>
                <div class="card-body">
                    <ul class="list-inline">
                        <li class="list-inline-item">
                            <input class="form-control" type="search" id="search" placeholder="Search" aria-label="Search" style="width: 350px">
                        </li>
                        <li class="list-inline-item" style="margin-left: 540px">
                            <a href="{{route('adminPlaces.create')}}" class="btn btn-primary">
                                <i class="plus icon"></i>
                                Tambah Obyek Wisata
                            </a>
                        </li>
                    </ul>
                    <table class="table table-bordered table-hover table-striped" style="font-size: 15px; text-align: center" align="center">
                        <thead>
                            <tr>
                                <th scope="col" style="font-size: 17px;">ID</th>
                                <th scope="col" style="font-size: 17px;">Nama</th>
                                <th scope="col" style="font-size: 17px;">Operasional</th>
                                <th scope="col" style="font-size: 17px;">Buka</th>
                                <th scope="col" style="font-size: 17px;">Tutup</th>
                                <th scope="col" style="font-size: 17px;">Tiket</th>
                                <th scope="col" style="font-size: 17px;">Gambar</th>
                                <th scope="col" style="font-size: 17px; width: 150px">Aksi</th>
                            </tr>
                        </thead>
                        @php
                            $no=1;
                        @endphp
                        <tbody id="tabel">
                            @foreach($place as $p)
                            <tr style="position: center center">
                                <td style="text-align: center center">{{$no++}}</td>
                                <td>{{ $p->nama }}</td>
                                <td>{{ $p->hari }}</td>
                                <td>{{ $p->buka}}</td>
                                <td>{{ $p->tutup }}</td>
                                <td>Rp {{ $p->harga_tiket}}</td>
                                <td><img width="150px" height="90px" src="{{ url('/images/'.$p->gambar) }}"></td>

                                <td style="font-size: 20px">
                                    <a href="{{ route('adminPlaces.edit', $p->id) }}"><i class="blue edit icon"></i></a> |
                                    <form action="{{ route('adminPlaces.destroy', $p->id)}}" method="post" class="d-inline">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" style="background-color: transparent; border: 0;" onclick="return confirm('Yakin hapus');"><i class="red trash alternate icon"></i></button>
                                    </form>   
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                        
                    </table>
                    {{ $place->links() }}
                </div>
            </div>
        </div>
@endsection