routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () 
{
    if(Auth::check() && auth::user()->isAdmin == 1)
    {
        return view('admin/index');

    }else if((Auth::check() && auth::user()->isAdmin != 1))
    {
        return redirect('/home');
    }else 
    {
        return view('/home');
    }
});

Auth::routes();

Route::post('/buyticket', 'TicketsController@store')->middleware('auth');


Route::resource('baskets', 'BasketsController');

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('places', 'PlacesController');
Route::resource('comments', 'CommentsController');
Route::resource('schedules', 'SchedulesController');
Route::resource('adminPlaces', 'AdminPlaceController');
Route::resource('adminUsers', 'AdminUserController');
Route::resource('Dates', 'DateController');
// Route::resource('tickets', 'TicketsController');

// Route::get('Places/show', 'CommentsController@index');
// Route::resource('Places.show', 'CommentsController');
// Route::get('/places/{places}', 'CommentsController@index');
// Route::get('Places/action', 'LiveSearchController@action')->name('Places.action');

app/Schedule.php
<?php

namespace App;

use App\Date;
use Illuminate\Database\Eloquent\Model;

class Schedule extends Model
{
    protected $dates = ['date'];
    protected $fillable =['id','user_id','place_id','date_id','day','hourStart','hourEnd'];

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function places()
    {
        return $this->belongsTo('App\Place', 'place_id');
    }

    public function date()
    {
        return $this->belongsTo('App\Date')->latest();
    }
    
    public $timestamps = false;
}

app/Http/Controllers/SchedulesController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use Carbon\Carbon;
use App\Place;
use App\Schedule;
use App\ScheduleDate;
use App\Date;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\Request;
use App\Http\Requests\CommentRequest;

class SchedulesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    public function index()
    {   
        
        $user = Auth::user();
        return view('Schedules.show', compact('user'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $place = Place::all();
        return view('Schedules/add', compact('place'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        $tmpt = $request->nama;
        $plc = Place::where('nama', 'like', "%".$request->nama."%")->first();
        $tgl = Date::where('date', 'like', "%".$request->date."%")->first();
        if($tgl==true){
            $schdl=Schedule::create([
                'date_id'=>$tgl->id,
                'place_id'=>$plc->id,
                'user_id'=>auth()->id(),
                'day' => $request->day,
                'hourStart' => $request->hourStart,
                'hourEnd' => $request->hourEnd,
        ]);
        }else{

            Date::create([
                'date' => $request->date,
                'created_at' => $request->date
            ]);

            $tgl2 = Date::where('date', 'like', "%".$request->date."%")->first();
            $schdl=Schedule::create([
                'date_id'=>$tgl2->id,
                'place_id'=>$plc->id,
                'user_id'=>auth()->id(),
                'day' => $request->day,
                'hourStart' => $request->hourStart,
                'hourEnd' => $request->hourEnd,
        ]);
        }
        session()->flash('notif', 'Jadwal Berhasil ditambahkan');


        return redirect()->route('schedules.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // $user = Date::all()->sortBy('date')->all();
        $user = Auth::user();
        return view('Schedules.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $place = Place::all();
        $scdl = Schedule::find($id);
        return view('Schedules/editSchedule', compact('scdl', 'place'));   
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {   
        $plc = Place::where('nama', 'like', "%".$request->nama."%")
            ->first();
        $tgl = Date::where('date', 'like', "%".$request->date."%")->first();

        if($tgl==true){
        $place = Schedule::find($id);
        $place->day  = $request->day;
        $place->hourStart  = $request->hourStart;
        $place->hourEnd  = $request->hourEnd;
        $place->date_id = $tgl->id;
        $place->place_id = $plc->id;
        $place->user_id   = auth()->id();
        }else{
            Date::create([
                'date' => $request->date,
            ]);
            $tgl2 = Date::where('date', 'like', "%".$request->date."%")->first();
            $place = Schedule::find($id);
            $place->day  = $request->day;
            $place->hourStart  = $request->hourStart;
            $place->hourEnd  = $request->hourEnd;
            $place->date_id = $tgl2->id;
            $place->place_id = $plc->id;
            $place->user_id   = auth()->id();
        }
        $place->save();

        session()->flash('notif', 'Jadwal Berhasil diubah');

        return redirect()->route('schedules.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $place = Schedule::find($id);
        $place->delete();

        return redirect()->route('schedules.index');    
    }

}

resources/views/Schedules/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
   <!-- Remove This Before You Start -->
    <h1>Tambah Jadwal</h1>
    <hr>
    @if (count($errors) > 0)
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <form action="{{ route('schedules.store') }}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}
        <div class="form-group">
            <div class="form-group">
                <label for="facl">Tanggal:</label>
                <input type="date" class="form-control" id="" name="date">
            </div>
            <label for="nama">Destinasi :</label>
            <input list="browsers" class="form-control"  name="nama">
            <datalist id="browsers">
                @foreach ($place as $item)
                    <option value="{{$item->nama}}" >
                @endforeach
            </datalist> 
        </div>

        <div class="form-group">
            <label for="day">Hari:</label>
            <input type="text" class="form-control" id="" name="day">
        </div>
        <div class="form-group">
            <label for="day">Dari Jam: </label>
            <input type="time" class="form-control" id="" name="hourStart">
        </div>
        <div class="form-group">
            <label for="open">Sampai Jam: </label>
            <input type="time" class="form-control" id="" name="hourEnd">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-md btn-primary">Submit</button>
            <button type="reset" class="btn btn-md btn-danger">Cancel</button>
        </div>
    </form>
    </div>
@endsection

resources/views/Schedules/editPlace.blade.php
@extends('layouts.appAdmin')

@section('content')
    <div class="container">
   <!-- Remove This Before You Start -->
   <h1>Ubah Destinasi Wisata</h1>
   <hr>
   @if (count($errors) > 0)
   <div class="alert alert-danger">
       <ul>
           @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
           @endforeach
       </ul>
   </div>
   @endif
   <form action="{{ route('adminPlaces.update', $place->id) }}" method="post" enctype="multipart/form-data">
       {{ csrf_field() }}
       @method('PUT')

       <div class="form-group">
           <label for="name">Nama Destinasi:</label>
           <input type="text" class="form-control" id="" name="name" value="{{$place->nama}}">
       </div>
       <div class="form-group ">
            <label for="day">Hari Buka: </label>
            <input type="text" class="form-control" id="" name="day" placeholder="contoh : senin-rabu & jumat-minggu" value="{{$place->hari}}">
        </div>
       <div class="form-group">
           <label for="open">Jam Buka: </label>
           <input type="time" class="form-control" id="" name="open" value="{{$place->buka}}">
       </div>
       <div class="form-group">
           <label for="close">Jam Tutup: </label>
           <input type="time" class="form-control" id="" name="close" value="{{$place->tutup}}">
       </div>
       <div class="form-group">
           <label for="price">Harga Tiket:</label>
           <input type="text" class="form-control" id="" name="price" value="{{$place->harga_tiket}}">
       </div>
       <div class="form-group">
            <label for="facl">Fasilitas:</label>
            <input type="text" class="form-control" id="" name="facl" value="{{$place->tempat_umum}}">
        </div>
       <div class="form-group">
            <label for="desc">Deskripsi:</label>
            <textarea class="form-control" id="alamat" name="desc">{{$place->deskripsi}}</textarea>
        </div>
        <div class="form-group">
            <label for="gambar">Masukkan File Gambar</label>
            <input type="file" name="gambar">
        </div>
       <div class="form-group">
           <button type="submit" class="btn btn-md btn-primary">Submit</button>
           <button type="reset" class="btn btn-md btn-danger">Cancel</button>
       </div>
   </form>

    </div>
@endsection

resources/views/Schedules/editSchedule.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
   <!-- Remove This Before You Start -->
   <h1>Edit Jadwal</h1>
   <hr>
   @if (count($errors) > 0)
   <div class="alert alert-danger">
       <ul>
           @foreach ($errors->all() as $error)
               <li>{{ $error }}</li>
           @endforeach
       </ul>
   </div>
   @endif
   <form action="{{ route('schedules.update' , $scdl->id) }}" method="post" enctype="multipart/form-data">
       {{ csrf_field() }}
       @method('PUT')
       <div class="form-group">
            <div class="form-group">
                    <label for="facl">Tanggal:</label>
                    <input type="date" class="form-control" id="" name="date" value="{{$scdl->date['date']}}">
               </div>
            <label for="nama">Destinasi :</label>
            <input list="browsers" class="form-control"  name="nama" value="{{$scdl->places['nama']}}">
            <datalist id="browsers">
                @foreach ($place as $item)
                    <option value="{{$item->nama}}" >
                @endforeach
           </datalist> 
        </div>

       <div class="form-group">
            <label for="day">Hari:</label>
       <input type="text" class="form-control" id="" name="day" value="{{$scdl->day}}">
        </div>
       <div class="form-group">
            <label for="day">Dari Jam: </label>
            <input type="time" class="form-control" id="" name="hourStart" value="{{$scdl->hourStart}}">
        </div>
       <div class="form-group">
           <label for="open">Sampai Jam: </label>
           <input type="time" class="form-control" id="" name="hourEnd" value="{{$scdl->hourEnd}}">
       </div>
       <div class="form-group">
           <button type="submit" class="btn btn-md btn-primary">Submit</button>
           <button type="reset" class="btn btn-md btn-danger">Cancel</button>
       </div>
   </form>

    </div>
@endsection

resources/views/Schedules/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container mt-4">
            <div class="card mt-2">
                <div class="card-header text-center">
                    <h2><strong>Jadwal Anda</strong></h2>
                </div>
                <div class="card-body">
                    <ul class="list-inline">
                        <li class="list-inline-item">
                            <input class="form-control" type="search" placeholder="Search" aria-label="Search" style="width: 350px">
                        </li>
                        <li class="list-inline-item" style="margin-left: 540px">
                            <a href="{{route('schedules.create')}}" class="btn btn-primary">
                                <i class="plus icon"></i>
                                Tambah Jadwal
                            </a>
                        </li>
                    </ul>
                    @if($user->schedules)
                    @foreach ($user->schedules as $p)
                    <table class="table table-bordered table-hover table-striped" style="font-size: 15px; text-align: center" align="center">
                            <thead>
                                <tr>
                                    <th colspan="2" class="w-50">{{date('d-m-Y', strtotime($p->date->date))}}</th>
                                    @php
                                        $date = date('d-m-Y', strtotime($p->date->date));
                                    @endphp
                                    <th colspan="2" class="w-35" id="demo">Waktu</th>
                                    <th>
                                        <form action="{{ route('Dates.destroy', $p->id)}}" method="post" class="d-inline">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" style="background-color: transparent; border: 0;" onclick="return confirm('Yakin hapus');"><i class="red trash alternate icon"></i></button>
                                        </form>  
                                    </th>

                                </tr>
                                <tr>
                                    <th scope="col" style="font-size: 17px;" class="w-25">Destinasi</th>
                                    <th scope="col" style="font-size: 17px;" class="w-25">Hari</th>
                                    <th scope="col" style="font-size: 17px;">Mulai</th>
                                    <th scope="col" style="font-size: 17px;">Sampai</th>
                                    <th scope="col" style="font-size: 17px; width: 150px">Aksi</th>
                                </tr>
                            </thead>
                        @php
                        $no=1;
                        @endphp
                        <tbody>
                            <tr style="position: center center">
                                    
                                {{-- <td>{{ Carbon\Carbon::parse($p->date['date'])->format('d-m-Y') }}</td> --}}
                                <td>{{ $p->places->nama }}</td>
                                <td>{{ $p->day }}</td>
                                <td>{{ $p->hourStart }}</td>
                                <td>{{ $p->hourEnd}}</td>
                                <td style="font-size: 20px">
                                    <a href="{{ route('schedules.edit', $p->id) }}"><i class="blue edit icon"></i></a> |
                                    <form action="{{ route('schedules.destroy', $p->id)}}" method="post" class="d-inline">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" style="background-color: transparent; border: 0;" onclick="return confirm('Yakin hapus');"><i class="red trash alternate icon"></i></button>
                                        </form>   
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    @endforeach
                    @else
                        <h2>Belum ada jadwal</h2>
                        <button class="btn btn-success">Buat Jadwal</button>
                    @endif
                </div>
            </div>
        </div>
@endsection